[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = ["Yufei Chen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.15"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"